import '../globals.css';
import { Navbar } from '../components/Navbar';
import { getCurrentUser } from '../utils/getCurrentUser';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const currentUser = await getCurrentUser();
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    );
}
